### ISSUE TITLE
Demo data test run failed.

### ISSUE THREAD

**Issue by Lix1993** [MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software#8]
this command fails:
```bash
/opt/conda/envs/rnaseq/bin/python /share/software/DNBelab_C_Series_scRNA-analysis-software/scripts/scRNA_scanpy_clustering.py /mnt/test/test_scRNA/test_DNBelab/run_demo/result/outs/count_mtx.tsv.gz /mnt/test/test_scRNA/test_DNBelab/run_demo/result/report/
```

error info:
````python
Trying to set attribute `.obs` of view, copying.
Traceback (most recent call last):
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/utils.py", line 188, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 194, in write_array
    f.create_dataset(key, data=value, **dataset_kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/h5py/_hl/group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 140, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 443, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 94, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 248, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/utils.py", line 188, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 288, in write_series
    write_array(group, category_key, categories, dataset_kwargs=dataset_kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/utils.py", line 191, in func_wrapper
    raise type(e)(
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key '__categories/__is_in_cluster__' of <class 'h5py._hl.group.Group'> from /.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/utils.py", line 188, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 268, in write_dataframe
    write_series(group, colname, series, dataset_kwargs=dataset_kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/utils.py", line 191, in func_wrapper
    raise type(e)(
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key '__categories/__is_in_cluster__' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key '__is_in_cluster__' of <class 'h5py._hl.group.Group'> from /.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/software/DNBelab_C_Series_scRNA-analysis-software/scripts/scRNA_scanpy_clustering.py", line 66, in <module>
    adata.write("%s/cluster.h5ad" % result_dir)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1844, in write_h5ad
    _write_h5ad(
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 118, in write_h5ad
    write_attribute(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 139, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/opt/conda/envs/rnaseq/lib/python3.8/site-packages/anndata/_io/utils.py", line 191, in func_wrapper
    raise type(e)(
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key '__categories/__is_in_cluster__' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key '__is_in_cluster__' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.

```

**Comment by Lix1993** [comment]
when comment out the last line,  `adata.write("%s/cluster.h5ad" % result_dir)`

pipeline  works well

so a certain version anndata or scanpy should be used.

Could you provide you python environment version info
